# Generated by Django 5.2.11 on 2026-03-15 05:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_usernotification_completioncheck'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='timetable_u_user_id_3bf139_idx',
            old_name='timetable_u_user_id_2fdf54_idx',
        ),
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='timetable_u_schedul_82c7e6_idx',
            old_name='timetable_u_schedul_08958d_idx',
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='freeslot',
            index=models.Index(fields=['user', 'start'], name='timetable_f_user_id_b626b8_idx'),
        ),
        migrations.AddIndex(
            model_name='freeslot',
            index=models.Index(fields=['user', 'end'], name='timetable_f_user_id_908627_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['user', 'start'], name='timetable_t_user_id_175e09_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['user', 'done', 'start'], name='timetable_t_user_id_e3f244_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['user', 'name'], name='timetable_t_user_id_bff2df_idx'),
        ),
    ]
