# Generated by Django 5.2.11 on 2026-03-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_document"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserModelSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_version", models.PositiveIntegerField(default=1)),
                ("feature_names", models.JSONField(blank=True, default=list)),
                ("weights", models.JSONField(blank=True, default=list)),
                ("mean_vector", models.JSONField(blank=True, default=list)),
                ("scale_vector", models.JSONField(blank=True, default=list)),
                ("bias", models.FloatField(default=0.0)),
                ("training_source", models.CharField(default="synthetic", max_length=24)),
                ("historical_samples", models.PositiveIntegerField(default=0)),
                ("synthetic_samples", models.PositiveIntegerField(default=0)),
                ("total_samples", models.PositiveIntegerField(default=0)),
                ("epochs", models.PositiveIntegerField(default=0)),
                ("train_loss", models.FloatField(default=0.0)),
                ("val_loss", models.FloatField(default=0.0)),
                ("val_accuracy", models.FloatField(default=0.0)),
                ("regularization", models.FloatField(default=0.02)),
                ("trained_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completion_model_snapshot",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-trained_at"]},
        ),
    ]
